### ISSUE TITLE
Verifiable PayID Protocol implemention

### ISSUE THREAD

**Issue by wshbair** [payid-org/rfcs#45]
Is the Verifiable PayID Protocol has been implemented in the current version of the PayID server?
I have a look on the code and found a function of verifiable but it not similar to what mentioned in this RFC.

**Comment by hbergren** [comment]
@wshbair , what was different between the PayID server and the RFC?

**Comment by wshbair** [comment]
For example, this is the return of API of GET request (http://127.0.0.1:8080/wazen)
`{
    "addresses": [],
    "verifiedAddresses": [
        {
            "signatures": [
                {
                    "name": "testing",
                    "protected": "",
                    "signature": "d2hhdCBhbSBJIGNvZGluZyB3aGF0IGlzIGxpZmUgcGxlYXNlIGhlbHA="
                }
            ],
            "payload": "{\"payId\":\"wazen$127.0.0.1\",\"payIdAddress\":{\"paymentNetwork\":\"XRPL\",\"environment\":\"TESTNET\",\"addressDetailsType\":\"CryptoAddressDetails\",\"addressDetails\":{\"address\":\"TVQWr6BhgBLW2jbFyqqufgq8T9eN7KresB684ZSHKQ3oDth\"}}}"
        }
    ],
    "payId": "wazen$127.0.0.1"
}`

**While in** RFC of [verifiable-payid-protocol.txt](https://github.com/payid-org/rfcs/blob/master/dist/spec/verifiable-payid-protocol.txt) Section 7.2 the example says the return looks like:
`
{
"messageType" : "PaymentInformation",
"message" :
 {
   "payId" : "bob$receiver.example.com",
   "addresses" :
   [
     {
       "paymentNetwork" : "xrpl",
       "environment" : "testnet",
       "addressDetailsType" : "CryptoAddressDetails",
       "addressDetails" : {
          "address" : "XTVQWr6BhgBLW2jbFyqqufgq8T9eN7KresB684ZSHKQ3oDth"
        }
      }
    ],
    "memo" : "Additional optional Information",
    "identity" : "TBD",
 }
"signature" : "TBD"
}
`

Thanks in advance for clarification

**Comment by hbergren** [comment]
The [Verifiable PayID Protocol](https://github.com/payid-org/rfcs/blob/master/dist/spec/verifiable-payid-protocol.txt) is a bit outdated in that we've moved away from `SignatureWrapper`.

The reference server supports the [Self-Sovereign Verifiable PayID](https://github.com/payid-org/rfcs/blob/master/dist/spec/self-sov-verifiable-payid-protocol.txt) format. Note that this is really just a [JWS](https://tools.ietf.org/html/rfc7515), so the `protected` and `signature` keys are base64 encoded, and the `payload` is stringified. In the PayID RFC they are shown unencoded and unstringified to help understand what is inside those keys.

**Comment by hbergren** [comment]
@aanchal4 , what do you think we should do to avoid confusion here?

**Comment by aanchal4** [comment]
Thanks @wshbair for pointing this out. 

@hbergren Ideally I would like to update the [Verifiable PayID Protocol](https://github.com/payid-org/rfcs/blob/master/dist/spec/verifiable-payid-protocol.txt) soon. In the mean time, the best way to avoid this confusion is to add the following to the respective RFCs.

1. "Obsoletes [Verifiable PayID Protocol](https://github.com/payid-org/rfcs/blob/master/dist/spec/verifiable-payid-protocol.txt)" to  [Self-Sovereign Verifiable PayID](https://github.com/payid-org/rfcs/blob/master/dist/spec/self-sov-verifiable-payid-protocol.txt)
2. "Updated by [Self-Sovereign Verifiable PayID](https://github.com/payid-org/rfcs/blob/master/dist/spec/self-sov-verifiable-payid-protocol.txt)" to  [Verifiable PayID Protocol](https://github.com/payid-org/rfcs/blob/master/dist/spec/verifiable-payid-protocol.txt)

Probably this not the ideal way, but would help avoid confusion until I update the [Verifiable PayID Protocol](https://github.com/payid-org/rfcs/blob/master/dist/spec/verifiable-payid-protocol.txt) draft. 

@sappenin What do you think?

**Comment by sappenin** [comment]
@aanchal4 that sounds fine to me. I created some tasks for this that we can track internally.

I'm going to close this issue as it seems to be resolved for purposes of the problem @wshbair was having (@wshbair if there's still a concern here, feel free to re-open).
